services:
  subscription_db:
    image: postgres:16-alpine
    container_name: subscription_db
    command: postgres -c 'max_connections=50'
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=subscription_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
    volumes:
      - subscription_db_data:/var/lib/postgresql/data
  subscription_app:
    container_name: subscription_app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://subscription_db:5432/subscription_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - subscription_db
    restart: always
volumes:
  subscription_db_data: {}
