spring:
  application:
    name: '@project.artefactId@'
  datasource:
    url: jdbc:postgresql://localhost:5434/subscription_db?reWriteBatchedInserts=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html